name: analysis
dependencies:
  - python==3.7.0
  - jupyter
  - jupyterlab
  - scipy==1.1.0
  - pandas==0.23.4
  - matplotlib
  - seaborn==0.9.0
  - click
  - scikit-learn==0.20.1
  - statsmodels==0.9.0
  - pandas-profiling
  - spyder-kernels
  - pip:
    - xlrd==0.9.0 # pd.read_excel
